-- AlterTable
ALTER TABLE "GenerationSession" ADD COLUMN     "fadeInMs" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fadeOutMs" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Video" ADD COLUMN     "fadeInMs" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fadeOutMs" INTEGER NOT NULL DEFAULT 0;
